---
title: Analytical Case Management
subtitle: Syllabus Day
author: Joe Mienko
institute: School of Social Work
#titlegraphic: uw_social.png
fontsize: 10pt
output:
 ioslides_presentation:
    smaller: true
    #logo: uw_social.png
    css: svm-ioslides-css.css    
 beamer_presentation:
    template: svm-latex-beamer.tex
    keep_tex: true
# toc: true
    slide_level: 2
---

# Introductions

## Getting to Know Each Other

1. What prior social work experience do you have?
2. What was your undergraduate major?
3. What are your future plans/professional interests?

# Syllabus

## **Current** Outline of the Course

```{r cars, echo = FALSE}
DiagrammeR::mermaid("
graph LR
A(<center>Investigative <br/> Measurement</center>)-->B{<center>Investigative <br/> Decisions</center>}
B-->C(<center>Psychometric <br/> Measurement</center>)
C-->D{<center>Treatment <br/> Decisions</center>}
D-->E(<center>Change <br/> Measurement</center>)
E-->F{<center>Permanency <br/> Decisions</center>}
")
```

## Syllabus is Still Subject to Change

Outstanding Questions 

1. How much time we need for each topic
2. Whether or not we will have "lab-time" on some days
3. Preferred Website (Do people love Canvas?)

## Next Meeting

Read the following documents and come prepared to discuss next week: 
  
  - [NASW Code of Ethics](https://www.socialworkers.org/About/Ethics/Code-of-Ethics/Code-of-Ethics-English)
  - Gary King, Robert O Keohane, and Sidney Verba. (1994). *Designing Social Inquiry: Scientific Inference in Qualitative Research.* Princeton: Princeton University Press.
  
Complete the following housekeeping activities prior to our next meeting: 

  - [Register for a CSDE Account](https://csde.washington.edu/netid/account/new.php/)
  - [Activate UW G Suite](https://itconnect.uw.edu/connect/email/google-apps/getting-started/#activate)
  - Pre-Test (Link Forthcoming via Email)

# Child Welfare <br/> Measurement

